import { FxDbDriverNS } from '@fiborm/db-driver';
import type { FibOrmSqlDDLSync__SQL } from './@types/SQL';
export declare function CREATE_TABLE(options: FibOrmSqlDDLSync__SQL.TableOptions, db_type: FxDbDriverNS.DriverType): string;
export declare function DROP_TABLE(options: FibOrmSqlDDLSync__SQL.TableOptions, db_type: FxDbDriverNS.DriverType): string;
export declare function CHECK_TABLE_HAS_COLUMN(options: FibOrmSqlDDLSync__SQL.CheckTableHasColumnOptions, db_type: FxDbDriverNS.DriverType): string;
export declare function ALTER_TABLE_ADD_COLUMN(options: FibOrmSqlDDLSync__SQL.AddColumnOptions, db_type: FxDbDriverNS.DriverType): string;
export declare function ALTER_TABLE_RENAME_COLUMN(opts: FibOrmSqlDDLSync__SQL.AlertColumnRenameOptions, db_type: FxDbDriverNS.DriverType): string;
export declare function ALTER_TABLE_MODIFY_COLUMN(options: FibOrmSqlDDLSync__SQL.AlterColumnOptions, db_type: FxDbDriverNS.DriverType): string;
export declare function ALTER_TABLE_DROP_COLUMN(options: FibOrmSqlDDLSync__SQL.AlterColumnOptions, db_type: FxDbDriverNS.DriverType): string;
export declare function CREATE_INDEX(options: FibOrmSqlDDLSync__SQL.IndexOptions, db_type: FxDbDriverNS.DriverType): string;
export declare function DROP_INDEX(options: FibOrmSqlDDLSync__SQL.IndexOptions, db_type: FxDbDriverNS.DriverType): string;
