import type { FibOrmSqlDDLSync__Dialect } from "../@types/Dialect";
export declare const hasCollectionSync: FibOrmSqlDDLSync__Dialect.Dialect['hasCollectionSync'];
export declare const hasCollection: FibOrmSqlDDLSync__Dialect.Dialect['hasCollection'];
/**
 * @no_test
 */
export declare const addPrimaryKeySync: FibOrmSqlDDLSync__Dialect.Dialect['addPrimaryKeySync'];
export declare const addPrimaryKey: FibOrmSqlDDLSync__Dialect.Dialect['addPrimaryKey'];
export declare const dropPrimaryKeySync: FibOrmSqlDDLSync__Dialect.Dialect['dropPrimaryKeySync'];
export declare const dropPrimaryKey: FibOrmSqlDDLSync__Dialect.Dialect['dropPrimaryKey'];
export declare const addForeignKeySync: FibOrmSqlDDLSync__Dialect.Dialect['addForeignKeySync'];
export declare const addForeignKey: FibOrmSqlDDLSync__Dialect.Dialect['addForeignKey'];
export declare const dropForeignKeySync: FibOrmSqlDDLSync__Dialect.Dialect['dropForeignKeySync'];
export declare const dropForeignKey: FibOrmSqlDDLSync__Dialect.Dialect['dropForeignKey'];
export declare const getCollectionColumnsSync: FibOrmSqlDDLSync__Dialect.Dialect['getCollectionColumnsSync'];
export declare const getCollectionColumns: FibOrmSqlDDLSync__Dialect.Dialect['getCollectionColumns'];
export declare const getCollectionPropertiesSync: FibOrmSqlDDLSync__Dialect.Dialect['getCollectionPropertiesSync'];
export declare const getCollectionProperties: FibOrmSqlDDLSync__Dialect.Dialect['getCollectionProperties'];
export declare const createCollectionSync: FibOrmSqlDDLSync__Dialect.Dialect['createCollectionSync'];
export declare const createCollection: FibOrmSqlDDLSync__Dialect.Dialect['createCollection'];
export declare const dropCollectionSync: FibOrmSqlDDLSync__Dialect.Dialect['dropCollectionSync'];
export declare const dropCollection: FibOrmSqlDDLSync__Dialect.Dialect['dropCollection'];
export declare const hasCollectionColumnsSync: FibOrmSqlDDLSync__Dialect.Dialect['hasCollectionColumnsSync'];
export declare const hasCollectionColumns: FibOrmSqlDDLSync__Dialect.Dialect['hasCollectionColumns'];
export declare const addCollectionColumnSync: FibOrmSqlDDLSync__Dialect.Dialect['addCollectionColumnSync'];
export declare const addCollectionColumn: FibOrmSqlDDLSync__Dialect.Dialect['addCollectionColumn'];
export declare const renameCollectionColumnSync: FibOrmSqlDDLSync__Dialect.Dialect['renameCollectionColumnSync'];
export declare const renameCollectionColumn: FibOrmSqlDDLSync__Dialect.Dialect['renameCollectionColumn'];
export declare const modifyCollectionColumnSync: FibOrmSqlDDLSync__Dialect.Dialect['modifyCollectionColumnSync'];
export declare const modifyCollectionColumn: FibOrmSqlDDLSync__Dialect.Dialect['modifyCollectionColumn'];
export declare const dropCollectionColumnSync: FibOrmSqlDDLSync__Dialect.Dialect['dropCollectionColumnSync'];
export declare const dropCollectionColumn: FibOrmSqlDDLSync__Dialect.Dialect['dropCollectionColumn'];
export declare const getCollectionIndexesSync: FibOrmSqlDDLSync__Dialect.Dialect['getCollectionIndexesSync'];
export declare const getCollectionIndexes: FibOrmSqlDDLSync__Dialect.Dialect['getCollectionIndexes'];
export declare const addIndexSync: FibOrmSqlDDLSync__Dialect.Dialect['addIndexSync'];
export declare const addIndex: FibOrmSqlDDLSync__Dialect.Dialect['addIndex'];
export declare const removeIndexSync: FibOrmSqlDDLSync__Dialect.Dialect['removeIndexSync'];
export declare const removeIndex: FibOrmSqlDDLSync__Dialect.Dialect['removeIndex'];
export declare const processKeys: FibOrmSqlDDLSync__Dialect.Dialect['processKeys'];
export declare const supportsType: FibOrmSqlDDLSync__Dialect.Dialect['supportsType'];
export declare const getType: FibOrmSqlDDLSync__Dialect.Dialect['getType'];
